In [8]:
n = 5
lam = [1, 1.5, .7, 1.2, .5]
v = [.18, .15, .25, .2, .3]
c = [5, 4, 3, 2, 1]
d = .01

mu = [1 / v[i] for i in range(n)]
v_2 = [d + v[i] ** 2 for i in range(n)]
psy = [lam[i] / mu[i] for i in range(n)]
R_N = sum(psy)
print("Коэффициент использования прибора любыми требованиями:", R_N)

w = 0.5 * sum([v_2[i] * lam[i] for i in range(n)]) / (1 - R_N)
print("Средняя продолжительность ожидания в каждой очереди:", w)
print("Среднее время ожидания произвольного заказа на обслуживание:", w)

b = [lam[i] * w for i in range(len(lam))]
[print('Среднее число заказов в', i + 1, 'очереди:', b[i]) for i in range(len(b))]
print('Средняя длина очереди:', sum(b))

cost_f = sum([c[i] * b[i] for i in range(len(b))])
print('Функция стоимости:', cost_f)

Коэффициент использования прибора любыми требованиями: 0.97
Средняя продолжительность ожидания в каждой очереди: 4.19833333333333
Среднее время ожидания произвольного заказа на обслуживание: 4.19833333333333
Среднее число заказов в 1 очереди: 4.19833333333333
Среднее число заказов в 2 очереди: 6.297499999999994
Среднее число заказов в 3 очереди: 2.9388333333333305
Среднее число заказов в 4 очереди: 5.037999999999996
Среднее число заказов в 5 очереди: 2.099166666666665
Средняя длина очереди: 20.571833333333316
Функция стоимости: 67.17333333333328


In [7]:
n = 5
lam = [1, 1.5, .7, 1.2, .5]
v = [.18, .15, .25, .2, .3]
c = [5, 4, 3, 2, 1]
d = .01

v_2 = [d + v[i] ** 2 for i in range(n)]
mu = [1 / v[i] for i in range(n)]
psy = [lam[i] / mu[i] for i in range(len(lam))]
R_N = []
s = 0
for i in range(n):
    s += psy[i]
    R_N.append(s)
print('R_N:', R_N)

w = []
for j in range(n):
    if j == 0:
        w.append((0.5 * sum([lam[i] * v_2[i] for i in range(n)])) /
                 (1 - R_N[j]))
    else:
        w.append((0.5 * sum([lam[i] * v_2[i] for i in range(n)])) /
                 ((1 - R_N[j - 1]) * (1 - R_N[j])))
print('Среднее время ожидания в очередях:', w)

w_random = sum([w[i] * lam[i] / sum(lam) for i in range(n)])
print('Среднее время ожидания произвольного заказа:', w_random)

b = [lam[i] * w[i] for i in range(n)]
[print('Среднее число заказов в', i + 1, 'очереди:', b[i]) for i in range(n)]
print('Средняя длина очереди:', sum(b))

F = sum([lam[i] * w[i] * c[i] for i in range(n)]) + sum([c[i] * psy[i] for i in range(n)])
print('F =', F)

fines = [c[i] / v[i] for i in range(n)]
print('Скорости извлечения прибором штрафов из СМО:', fines)

R_N: [0.18, 0.40499999999999997, 0.58, 0.82, 0.97]
Среднее время ожидания в очередях: [0.15359756097560975, 0.2581471613035458, 0.5040016006402561, 1.6660052910052905, 23.324074074074048]
Среднее время ожидания произвольного заказа: 2.9703801652290776
Среднее число заказов в 1 очереди: 0.15359756097560975
Среднее число заказов в 2 очереди: 0.38722074195531875
Среднее число заказов в 3 очереди: 0.35280112044817924
Среднее число заказов в 4 очереди: 1.9992063492063485
Среднее число заказов в 5 очереди: 11.662037037037024
Средняя длина очереди: 14.554862809622481
F = 21.99072386949358
Скорости извлечения прибором штрафов из СМО: [27.77777777777778, 26.666666666666668, 12.0, 10.0, 3.3333333333333335]


In [5]:
n = 5
# начальные условия
lam = [1, 1.5, .7, 1.2, .5]
v = [.18, .15, .25, .2, .3]
c = [5, 4, 3, 2, 1]
d = .01

mu = [1 / v[i] for i in range(n)]
print('mu:', mu)

v_2 = [d + v[i] ** 2 for i in range(n)]
print('v_2:', v_2)

psy = [lam[i] / mu[i] for i in range(n)]
R_N = []
s = 0
for i in range(n):
    s += psy[i]
    R_N.append(s)
print('R_N:', R_N)

theta = [v[j] / (1 - R_N[j - 1]) for j in range(n)]
theta[0] = v[0]
print('theta:', theta)

delta = [v_2[i] / (2 * v[i]) for i in range(n)]
sigma = []
s = 0
for i in range(n):
    s += psy[i] * delta[i]
    sigma.append(s)

w = [sigma[0] / (1 - R_N[0])]
for i in range(1, n):
    w.append(sigma[i] / ((1 - R_N[i - 1]) * (1 - R_N[i])))
print('Средняя продолжительность ожидания обработки инф. каждого типа:\n', w)

w_random = sum([w[i] * lam[i] / sum(lam) for i in range(n)])
print('Средняя продолжительность ожидания обработки инф. из общего потока:\n', w_random)

F = sum([c[i] * lam[i] * w[i] for i in range(n)])
print('F:', F)
# условия оптимизации абсолютных приоритетов
cond1 = [c[i] / v[i] for i in range(n)]
print("Первое условие:", cond1)

cond2 = [2 * v[i] * c[i] / v_2[i] for i in range(n)]
print("Второе условие:", cond2)

print('\tВторое условие\t\tПервое условие')
for i in range(n):
    print("i =", i, ":", round(cond2[i], 3), '\t\t', round(cond1[i], 3))

mu: [5.555555555555555, 6.666666666666667, 4.0, 5.0, 3.3333333333333335]
v_2: [0.0424, 0.0325, 0.0725, 0.05000000000000001, 0.09999999999999999]
R_N: [0.18, 0.40499999999999997, 0.58, 0.82, 0.97]
theta: [0.18, 0.18292682926829265, 0.42016806722689076, 0.47619047619047616, 1.666666666666666]
Средняя продолжительность ожидания обработки инф. каждого типа:
 [0.025853658536585365, 0.09341053494568559, 0.28391356542617047, 1.33531746031746, 23.324074074074048]
Средняя продолжительность ожидания обработки инф. из общего потока:
 2.7814544788104913
F: 16.152748931550924
Первое условие: [27.77777777777778, 26.666666666666668, 12.0, 10.0, 3.3333333333333335]
Второе условие: [42.45283018867924, 36.92307692307692, 20.689655172413794, 15.999999999999998, 6.0]
	Второе условие		Первое условие
i = 0 : 42.453 		 27.778
i = 1 : 36.923 		 26.667
i = 2 : 20.69 		 12.0
i = 3 : 16.0 		 10.0
i = 4 : 6.0 		 3.333


In [1]:
mu_1 = 10
mu_2 = 8
lambd = 15
phi = 1

alpha = lambd / (mu_1 + mu_2)
beta = mu_2 / mu_1

temp_1 = alpha / (1 + 2 * alpha)
temp_2 = 1 / beta
temp_3 = 1 + (1 + beta ** 2) * alpha - (1 - beta ** 2) * phi

p_00 = (1 - alpha) / (1 + temp_1 * temp_2 * temp_3)
print('Вероятность того, что оба продовца свободны:', p_00)

# вероятность того, что первый продавец занят обслуживанием покупателей, а второй свободен (и наоборот)
p_10 = temp_1 * (1 + beta) * (alpha + phi) * p_00
print('Вероятность того, что первый продавец занят, а второй свободен:', p_10)
p_01 = temp_1 * ((1 + beta) / beta) * (alpha + 1 - phi) * p_00
print('Вероятность того, что первый свободен, а второй продавец занят:', p_01)
# доля рабочего времени, когда оба продовца будут свободны (заняты)
p_busy = 1 - p_00 - (p_10 + p_01)
print('Доля р.в., когда оба продовца заняты =', p_busy)
p_free = p_00
print('Доля р.в., когда оба продовца свободны =', p_free)

# вероятность того, что в магазине больше 3 покупателей
p_2 = (alpha ** 2 / (1 + 2 * alpha)) * ((1 + beta) / beta) * (1 + (1 + beta) * alpha - (1 - beta) * phi) * p_00
p_3 = (alpha ** 3 / (1 + 2 * alpha)) * ((1 + beta) / beta) * (1 + (1 + beta) * alpha - (1 - beta) * phi) * p_00
p_m = 1 - (p_00 + p_01 + p_10 + p_2 + p_3)
print('Вероятность того, что в магазине больше 3 покупателей:', p_m)

# среднее число покупателей в магазине
temp_1 = alpha * (1 + beta) / (1 - alpha)
temp_2 = 1 + (1 + beta) * alpha - (1 - beta) * phi
temp_3 = beta * (1 + 2 * alpha) + alpha * (1 + (1 + beta ** 2) * alpha - (1 - beta ** 2) * phi)

n = temp_1 * (temp_2 / temp_3)
print('Среднее число покупателей в магазине:', n)

# среднее время ожидания покупателя в очереди
h = (p_01 + p_10) + 2 * p_busy
b = n - h
w = b / lambd
print('Среднее время ожидания покупателя в очереди:', w)

# среднее время пребывания покупателя в магазине
u = n / lambd
print('Среднее время пребывания покупателя в магазине:', u)

Вероятность того, что оба продовца свободны: 0.09343065693430654
Вероятность того, что первый продавец занят, а второй свободен: 0.09635036496350362
Вероятность того, что первый свободен, а второй продавец занят: 0.054744525547445244
Доля р.в., когда оба продовца заняты = 0.7554744525547445
Доля р.в., когда оба продовца свободны = 0.09343065693430654
Вероятность того, что в магазине больше 3 покупателей: 0.5246350364963505
Среднее число покупателей в магазине: 5.43941605839416
Среднее время ожидания покупателя в очереди: 0.25182481751824815
Среднее время пребывания покупателя в магазине: 0.36262773722627734


In [1]:
from math import exp, factorial
import numpy as np

N = 2
lam = 1.5
nu = 0.5
mu = 1 / nu

alpha = lam / mu
print('alpha:', alpha)


def p1n(_n):
    return (alpha * sum([alpha ** (-i) for i in range(N - _n + 1)])) / ((N + 1) * exp(alpha) + sum([(N - i + 1) * alpha ** (-i) for i in range(1, N+1)]))


def pkn(_k):
    return ((alpha ** _k) / factorial(_k)) / ((N + 1) * exp(alpha) + sum([(N - i + 1) * alpha ** (-i) for i in range(1, N+1)]))


# а) вероятность того, что у раздат. окна инструм. кладовой никого из рабочих нет, и дежурный кладовщик свободен от выдачи
p_1_0 = p1n(0)
p_0_0 = p_1_0 / alpha
print('Вероятность того, что у раздат. окна инструм. кладовой никого из рабочих нет, и дежурный кладовщик свободен от выдачи:\n', p_0_0)

# б) вероятности того, что на раздаче инструмента будет занято 1,2,3,...,7 кладовщиков
p_1_1 = p1n(1)
p_1_2 = p1n(2)
p = [
    [p_1_0],
    [p_1_1],
    [p_1_2]
]

for i in range(N+1):
    for k in range(2, 8):
        p[i].append(pkn(k))
        
p = np.array(p)
p_k = [p.transpose()[k].sum() for k in range(7)]

print('\nВероятности того, что на раздаче инструмента будет занято 1,2,3,...,7 кладовщиков:\n')
for k in range(7):
    print('p(', k + 1, ', n) = ', round(p_k[k], 5), ', где n = 0,1,2.', sep='')
    
# в) вероятности того, что очередь не будет превышать N человек при условии,
# что на раздаче инструмента будет занято 1,2,3,...,7 кладовщиков
print('\nВероятности того, что очередь не будет превышать N человек при условии, что на раздаче инструмента будет занято 1,2,3,...,7 кладовщиков:\n')

p_N = [p_0_0] * 7
for n in range(N + 1):
    for k in range(7):
        p_N[k] += p[n][k]

[print("Вероятности того, что очередь не будет превышать 2 человек при условии, что на раздаче инструмента будет занято", k + 1, 'кладовщиков:', round(p_N[k], 4)) for k in range(len(p_N))]

# г) среднее число занятых кладовщиков
h = sum([p1n(n) for n in range(N + 1)]) + sum([k * sum([pkn(k) for _ in range(N + 1)]) for k in range(2, 150)])
print('М.о. числа занятых кладовщиков:', h)

# д) среднее число рабочих, ожидающих в очереди
b = sum([n * p1n(n) for n in range(N + 1)]) + sum([sum([n * pkn(k) for n in range(N + 1)]) for k in range(2, 150)])
print('М.о. числа рабочих, ожидающих в очереди:', b)

# е) среднее время пребывания рабочих в очереди в ожидании выдачи инструмента
w = b / lam
print('М.о. времени пребывания рабочих в очереди:', w)

# среднее число кладовщиков с условием
a = 80 / 100
s = p_0_0
k = 0
while s < a:
    s += p_k[k]
    k += 1

print(f'В среднем необходимо {k} кладовщиков, чтобы обеспечить обслуживание рабочих в заданных условиях с гарантийной веоятностью не ниже 0.8')

alpha: 0.75
Вероятность того, что у раздат. окна инструм. кладовой никого из рабочих нет, и дежурный кладовщик свободен от выдачи:
 0.3808190680141476

Вероятности того, что на раздаче инструмента будет занято 1,2,3,...,7 кладовщиков:

p(1, n) = 0.51719, где n = 0,1,2.
p(2, n) = 0.07816, где n = 0,1,2.
p(3, n) = 0.01954, где n = 0,1,2.
p(4, n) = 0.00366, где n = 0,1,2.
p(5, n) = 0.00055, где n = 0,1,2.
p(6, n) = 7e-05, где n = 0,1,2.
p(7, n) = 1e-05, где n = 0,1,2.

Вероятности того, что очередь не будет превышать N человек при условии, что на раздаче инструмента будет занято 1,2,3,...,7 кладовщиков:

Вероятности того, что очередь не будет превышать 2 человек при условии, что на раздаче инструмента будет занято 1 кладовщиков: 0.898
Вероятности того, что очередь не будет превышать 2 человек при условии, что на раздаче инструмента будет занято 2 кладовщиков: 0.459
Вероятности того, что очередь не будет превышать 2 человек при условии, что на раздаче инструмента будет занято 3 кладовщиков

In [2]:
import numpy as np

lambd = 3
mu_1 = 2
mu_2 = 1
N = 1
states = [(0, 0), (0, 1), (1, 0), (1, 1), (1, 2), (2, 1), (2, 2)]
print(f'Пространство состояний:\n{states}')
coef = np.zeros((7,7))
coef[0][0] = -lambd
coef[0][2], coef[1][3], coef[4][6]= [mu_1]*3
coef[0][1], coef[2][3], coef[5][6] = [mu_2]*3
coef[1][1] = -(lambd + mu_2)
coef[2][2] = -(lambd + mu_1)
coef[2][0], coef[3][2], coef[3][1], coef[5][3], coef[6][5], coef[6][4] = [lambd]*6
coef[3][3], coef[4][4], coef[5][5], coef[6][6] = [-(lambd + mu_1 + mu_2)]*4
coef[3][4], coef[3][5] = [mu_1 + mu_2]*2
coef[6][6] = -(mu_1 + mu_2)
print(f'Матрица коэффициентов СЛАУ:\n{coef}')
E = np.eye(7)
A = coef.T - E
A[6, :] = np.ones(7)
B = [[0]]*6
B.append([1])
p = np.linalg.solve(A, B)
print(f'Вектор стационарных вероятностей:\n{p}')
print(f'Сумма компонент вектора p = {np.sum(p)}')
p_refuse = p[-1]
print(f'А) Вероятность отказа: {p_refuse}')
count = float((1 - p[-1]) * 100)
print(f'Б) Доля выполненых заказов: {count:.3f}%')
p_over_1 = 1 - p[0] - p[1]
p_over_2 = 1 - p[0] - p[2]
print(f'В) Вероятность загруженности первого потока: {p_over_1}\n\
Вероятность загруженности второго потока: {p_over_2}')
n_1 = (p[2] + p[3] + p[4]) + 2*(p[5] + p[6])
n_2 = (p[1] + p[3] + p[5]) + 2*(p[4] + p[6])
n_ = 2*p[3] + 2*2*p[6] + (p[1] + p[2]) + 3*(p[4] + p[5])
print(f'Г) Среднее число машин, находящихся в первом потоке: {n_1}\n\
Среднее число машин в мастерской: {n_}')
h = 0 * p[0] + 1 * (p[1] + p[2]) + 2 * (p[3] + p[4] + p[5] + p[6])
b = n_ - h
print(f'Д) Среднее число машин, ожидающих обслуживания, в первом и во втором потоках: {b}')
t_free = float(p[0]*100)
print(f'Е) Доля времени простоя: {t_free:.3f}%')

Пространство состояний:
[(0, 0), (0, 1), (1, 0), (1, 1), (1, 2), (2, 1), (2, 2)]
Матрица коэффициентов СЛАУ:
[[-3.  1.  2.  0.  0.  0.  0.]
 [ 0. -4.  0.  2.  0.  0.  0.]
 [ 3.  0. -5.  1.  0.  0.  0.]
 [ 0.  3.  3. -6.  3.  3.  0.]
 [ 0.  0.  0.  0. -6.  0.  2.]
 [ 0.  0.  0.  3.  0. -6.  1.]
 [ 0.  0.  0.  0.  3.  3. -3.]]
Вектор стационарных вероятностей:
[[0.05560132]
 [0.07784185]
 [0.07413509]
 [0.11120264]
 [0.18286656]
 [0.18286656]
 [0.315486  ]]
Сумма компонент вектора p = 1.0
А) Вероятность отказа: [0.315486]
Б) Доля выполненых заказов: 68.451%
В) Вероятность загруженности первого потока: [0.86655684]
Вероятность загруженности второго потока: [0.87026359]
Г) Среднее число машин, находящихся в первом потоке: [1.36490939]
Среднее число машин в мастерской: [2.73352554]
Д) Среднее число машин, ожидающих обслуживания, в первом и во втором потоках: [0.99670511]
Е) Доля времени простоя: 5.560%


In [1]:
import numpy as np

lambd = 2
mu_1 = 2
mu_2 = 1
N = 3
states = [(0, 0), (0, 1), (1, 0), (1, 1), (1, 2), (2, 1), (2, 2), (2, 3), (3, 2), (3, 3), (3, 4), (4, 3), (4, 4)]
print(f'Пространство состояний:\n{states}')
coef = np.zeros((13,13))
coef[0][0] = -lambd
coef[0][2], coef[1][3], coef[4][6], coef[7][9], coef[10][12] = [mu_1]*5
coef[0][1], coef[2][3], coef[5][6], coef[8][9], coef[11][12] = [mu_2]*5
coef[1][1] = -(lambd + mu_2)
coef[2][2] = -(lambd + mu_1)
coef[2][0], coef[3][2], coef[3][1], coef[5][3], coef[6][5], coef[6][4], coef[8][6], coef[9][8], coef[9][7], coef[11][9], coef[12][11], coef[12][10] = [lambd]*12
coef[3][3], coef[4][4], coef[5][5], coef[6][6], coef[7][7], coef[8][8], coef[9][9], coef[10][10], coef[11][11] = [-(lambd + mu_1 + mu_2)]*9
coef[3][4], coef[3][5], coef[6][7], coef[6][8], coef[9][10], coef[9][11] = [mu_1 + mu_2]*6
coef[12][12] = -(mu_1 + mu_2)
print(f'Матрица коэффициентов СЛАУ:\n{coef}')
E = np.eye(13)
A = coef.T - E
A[12, :] = np.ones(13)
B = [[0]]*12
B.append([1])
p = np.linalg.solve(A, B)
print(f'Вектор стационарных вероятностей:\n{p}')
print(f'Сумма компонент вектора p = {np.sum(p)}')
p_refuse = p[-1]
print(f'А) Вероятность отказа: {p_refuse}')
count = float((1 - p[-1]) * 100)
print(f'Б) Доля выполненых заказов: {count:.3f}%')
p_over_1 = 1 - p[0] - p[1]
p_over_2 = 1 - p[0] - p[2]
print(f'В) Вероятность загруженности первого потока: {p_over_1}\n\
Вероятность загруженности второго потока: {p_over_2}')
n_1 = (p[2] + p[3] + p[4]) + 2*(p[5] + p[6] + p[7]) + 3*(p[8] + p[9] + p[10]) + 4*(p[11] + p[12])
n_2 = (p[1] + p[3] + p[5]) + 2*(p[4] + p[6] + p[8]) + 3*(p[7] + p[9] + p[11]) + 4*(p[10] + p[12])
n_ = 2*p[3] + 2*2*p[6] + 2*3*p[9] + 2*4*p[12] + (p[1] + p[2]) + 3*(p[4] + p[5]) + 5*(p[7] + p[8]) + 7*(p[10]+p[12])
print(f'Г) Среднее число машин, находящихся в первом потоке: {n_1}\n\
Среднее число машин в мастерской: {n_}')
h = 0 * p[0] + 1 * (p[1] + p[2]) + 2 * (p[3] + p[4] + p[5] + p[6] + p[7] + p[8] + p[9] + p[10] + p[11] + p[12])
b = n_ - h
print(f'Д) Среднее число машин, ожидающих обслуживания, в первом и во втором потоках: {b}')
t_free = float(p[0]*100)
print(f'Е) Доля времени простоя: {t_free:.3f}%')

Пространство состояний:
[(0, 0), (0, 1), (1, 0), (1, 1), (1, 2), (2, 1), (2, 2), (2, 3), (3, 2), (3, 3), (3, 4), (4, 3), (4, 4)]
Матрица коэффициентов СЛАУ:
[[-2.  1.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -3.  0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0. -4.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  2. -5.  3.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -5.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  2. -5.  3.  3.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -5.  0.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.  0. -5.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  2.  2. -5.  3.  3.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -5.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  2.  0. -5.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  2.  2. -3.]]
Вектор стационарных вероятностей:
[[0.00106087]
 [0.00172391]
 [0.0015913 ]
 [0.00291738]
 [0.0062326 ]
 [0.0062326 ]
 [0.01432